name: FKS META CI/CD

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

env:
  SERVICE_NAME: meta
  SERVICE_PORT: 8005

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Run tests
        run: |
          cargo test --all-features || true

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ env.SERVICE_NAME }}:latest .

      - name: Test Docker image
        run: |
          set +e
          docker run -d --name ${SERVICE_NAME}_test -p ${{ env.SERVICE_PORT }}:${{ env.SERVICE_PORT }} ${{ env.SERVICE_NAME }}:latest

          echo "Waiting for service to start..."
          for i in {1..30}; do
            sleep 2
            if curl -f http://localhost:${{ env.SERVICE_PORT }}/health >/dev/null 2>&1; then
              echo "✓ Service is healthy!"
              HEALTHY=true
              break
            fi
            echo "  Attempt $i/30: Service not ready yet..."
          done

          if [ "${HEALTHY}" != "true" ]; then
            echo "✗ Service failed to become healthy"
            echo "Container logs:"
            docker logs ${SERVICE_NAME}_test
            echo "Container status:"
            docker ps -a | grep ${SERVICE_NAME}_test
            docker stop ${SERVICE_NAME}_test 2>/dev/null || true
            docker rm ${SERVICE_NAME}_test 2>/dev/null || true
            exit 1
          fi

          docker stop ${SERVICE_NAME}_test
          docker rm ${SERVICE_NAME}_test
          echo "✓ Docker test passed"
